# -*- coding: utf-8 -*-
"""Answers for assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXHM_Hq9ZTrNY1dqXFsq8otElTJjtdCt

QN1.Ans
"""

Name = "WALTER"
Age = 25
answer = f"My name is {Name} and I am {Age} years old"
print(answer)

Number = 10.0
if Number > 10:
    Output = "Greater"
elif Number < 10:
    Output = "Lesser"
else:
    Output = "Equal"
print(Output)

n = 3
total = 0
for i in range(1, n + 1):
    total += i
print(total)

"""QN2.Ans"""

numbers = [3, 5, 7, 11]
list_sum = sum(numbers)
list_max = max(numbers)
list_min = min(numbers)
print(list_sum,
      list_max,
      list_min)

students = {"Egito": 73,
            "Hussein": 67,
            "Majobo": 82,
            "WALTER":99}

students_above_80 = []

for student in students:
    if students[student] > 80:
        students_above_80.append(student)

# Print the result
print(students_above_80)

list1 = [1, 2, 3, 4]
list2 = [3, 4, 5, 6]
common_elements = set(list1) & set(list2)
print(common_elements)

"""Qn3.Ans"""

# b value should not be 0
a = 13
b = 2

sum_result = a + b
difference = a - b
product = a * b
quotient = a / b
print(sum_result,
      difference,
      product,
      quotient)

x = True
y = False
logical_and = x and y
logical_or = x or y
logical_not_x = not x
print(logical_and,
      logical_or,
      logical_not_x)

